config/routes.rb
Rails.application.routes.draw do
  get 'funcionario/index'

  get 'cliente/index'

  devise_for :clientes
  devise_for :funcionarios
  resources :produtos
  
  
  root 'produtos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:descricao, :preco, :caminho, :tipo)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(produto) do |f| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="field">
    <%= f.label :preco %>
    <%= f.text_field :preco %>
  </div>

  <div class="field">
    <%= f.label :caminho %>
    <%= f.text_field :caminho %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<% if funcionario_signed_in? %>
            <div>
                <%= link_to 'New Produto', new_produto_path, class: "btn btn btn-default btn-sm"%>
                <a class="btn btn btn-default btn-sm" href="cliente/index">Listagem Clientes</a>
                <a class="btn btn btn-default btn-sm" href="funcionario/index">Listagem Funcionários</a>
            </div>

            <h1>Listage de Produtos</h1>

            <% @produtos.each do |produto| %>
            
                  <div class="col-sm-4 col-lg-4 col-md-4">
                      <div class="thumbnail">
                              <img src="<%= produto.caminho %>" alt="">
                              <div class="caption">
                                  <h4><a href="#"><%= produto.descricao %></a></h4>
                                  <button type="button" class="btn btn-primary btn-lg btn-block"><span>R$  </span><%= produto.preco %></button>
                              </div>
                              <div style="padding-left:40px; padding-bottom:15px;">
                                 
                                  <a class="btn btn-default btn-sm" href="produtos/<%= produto.id %>">Ver</a>
                                  <a class="btn btn-default btn-sm" href="<%= edit_produto_path(produto) %>">Editar</a>
                                  <%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Você tem certeza disso?' }, class: "btn btn-default btn-sm" %>
                                  
                              </div>
                      </div>
                  </div>
            <% end %>

<% elsif cliente_signed_in? %>
      
            <% @produtos.each do |produto| %>
      
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src="<%= produto.caminho %>" alt="">
                    <div class="caption">
                        <h4><a href="#"><%= produto.descricao %></a></h4>
                        <button type="button" class="btn btn-primary btn-lg btn-block"><span>R$  </span><%= produto.preco %></button>
                    </div>
                    
                      <div style="padding-left:80px; padding-bottom:15px;">
                         
                          <a class="btn btn-success btn-sm" href="">Comprar</a>

                      </div>
        
                </div>
            </div>
      
            <% end %>
            
<% else %>

            <% @produtos.each do |produto| %>
      
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src="<%= produto.caminho %>" alt="">
                    <div class="caption">
                        <h4><a href="#"><%= produto.descricao %></a></h4></button>
                        <button type="button" class="btn btn-primary btn-lg btn-block"><span>R$  </span><%= produto.preco %></button>
                    </div>
                    
                      <div style="padding-left:80px; padding-bottom:15px;">
                         
                          <!--<a class="btn btn-success btn-sm" href="">Comprar</a>-->

                      </div>
        
                </div>
            </div>
      
            <% end %>

<% end %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Cminho:</strong>
  <%= @produto.caminho %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @produto.tipo %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>