config/routes.rb
Rails.application.routes.draw do
  get 'funcionario/index'

  get 'cliente/index'

  devise_for :clientes
  devise_for :funcionarios
  resources :produtos
  
  
  root 'produtos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce_Carlin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    
    
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/shop-homepage.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

  </head>

  <body>
    
    <!-- Navigation -->
    <nav class="navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to(image_tag("Logo.png", :alt => "Logo", :title => "Logo"),"/") %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                
              <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Pesquisar...">
                    <span class="input-group-btn">
                         <button class="btn btn-secondary" type="button">Buscar</button>
                     </span>
                    </div>
                </div>

            
                <div class="botao-login">
                    
                <% if funcionario_signed_in? %>
                 
                 <%= link_to 'Logout', destroy_funcionario_session_path, method: :delete, class: "btn btn-default" %>
                 <%= link_to 'Login', new_funcionario_session_path, class: "btn btn-default disabled"%>
                 <%= link_to 'Cadastrar Novo', new_funcionario_registration_path, class: "btn btn-default disabled " %>
                 <%= link_to 'Área Privativa', new_funcionario_registration_path, class: "btn btn-default disabled "%>
                 
                 <% elsif cliente_signed_in?  %>
                 
                 <%= link_to 'Logout', destroy_cliente_session_path, method: :delete, class: "btn btn-default" %>
                 <%= link_to 'Login', new_cliente_session_path, class: "btn btn-default disabled"%>
                 <%= link_to 'Cadastrar-se', new_cliente_registration_path, class: "btn btn-default disabled " %>
                 <%= link_to 'Área Privativa', new_funcionario_session_path, class: "btn btn-default disabled"%>
                 
                 <% else %>
                 
                 <%= link_to 'Logout', destroy_cliente_session_path, method: :delete, class: "btn btn-default disabled" %>
                 <%= link_to 'Login', new_cliente_session_path, class: "btn btn-default "%>
                 <%= link_to 'Cadastrar-se', new_cliente_registration_path, class: "btn btn-default " %>
                 <%= link_to 'Área Privativa', new_funcionario_session_path, class: "btn btn-default "%>
                 
                 <% end %>
                 
                </div>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            
            <div class="col-md-3">
                <p class="lead">Carlim store melhores produtos</p>
                <div class="list-group">
                    <a href="#" class="list-group-item">Notebooks</a>
                    <a href="#" class="list-group-item">Celulares</a>
                    <a href="#" class="list-group-item">Cameras</a>
                </div>
            </div>
            
            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12" margin-left:"500px">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://bests10.com/cdn/ASUS-RoG-G751JY-3075e59d52a4c09c235c5fac13fd01c3.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://www.fudzilla.com/images/stories/2016/Reviews/Martian_A8_notebook/right.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="https://www.thetechlounge.com/wp-content/uploads/2017/05/asus-zenbook-flip-ux360ca.png" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                    
                </div>
                    <%= yield %>
            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <center><p>Copyright &copy; Carlos 2017</p></center>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
        
  </body>
</html>